### ISSUE TITLE
Help setting up a Golang adapter

### ISSUE THREAD

**Issue by akinsho** [rcarriga/neotest#6]
Hi @rcarriga,

Great work on this plugin 🚀, really excited to see how it evolves.

I've been trying to get it working with `go` and have been having some trouble, having read the explanation in the README and also dug through the code of this repo and the existing adapters.

I've got the project over here https://github.com/akinsho/neotest-go (happy to move it under a more general namespace if you intend to create a `neotest` org since I'm sure other people might want to contribute eventually, and I might stop working with go 🤷🏿)

I've added a sub folder (neogit_go) within the repo which adds two simple examples of tests and am trying to get things working using those.

Reference: https://pkg.go.dev/testing

### Issues
- [x] Detecting multiple test functions doesn't always work, sometimes it only works if there is one test in the file, and sometimes only works if there are multiple
- [x] It's not entirely clear how results should be returned, I assumed as a list of `neotest.Result[]` but tests seem to still show as pending when I return this list, so something seems to be missing
- [ ] How to handle test cases specified using a table or a list or struct (map) e.g.
(I'm guessing this case might not be possible, since it's not clear how to consistently determine what is a test case in the snippet below)
```go
package add
import "testing"
func TestAdd(t *testing.T) {
    cases := []struct {
        desc     string
        a, b     int
        expected int
    }{
        {"TestBothZero", 0, 0, 0},
        {"TestBothPositive", 2, 5, 7},
        {"TestBothNegative", -2, -5, -7},
    }
    for _, tc := range cases {
        actual := add(tc.a, tc.b)
        if actual != tc.expected {
            t.Fatalf("%s: expected: %d got: %d for a: %d and b %d",
                tc.desc, actual, tc.expected, tc.a, tc.b)
        }
    }
}
```
Any advice or pointers would be much appreciated

**Comment by rcarriga** [comment]
Hey thanks for looking to create an adapter! I've considered a separate org for them and will probably do that, just need to get some time to do so, hopefully this week. Probably should have that before releasing but to be honest, I didn't expect people to be so fast to start developing adapters :sweat_smile: 

To answer your questions:
1. I believe this was due to a small bug in the core when multiple adapters were present. You should see this fixed now in the latest commit.
2. The return type of `results` should be a `table<string, neotest.Result>` (see here https://github.com/rcarriga/neotest/blob/master/lua/neotest/adapters/interface.lua#L32) which maps the test IDs to results. Otherwise the core has no way to no what result corresponds to what result.
3. Had the same issue of dynamic tests for neotest-plenary and I suspect this will be a problem in other languages too. I know VSCode's Jest integration will actually show the dynamic tests as separate tests but that requires a very strong integration which I think is overkill. Instead what I did for neotest-plenary was to check where the dynamic test was created (using the debug module) and matched it to the range of a static test. When constructing results the result object allows for multiple error messages so that multiple dynamic tests results can be aggregated in one. So for your example the result for `TestAdd` would contain the errors for `TestBothZero`, `TestBothPositive` and `TestBothNegative`. Of course this is just a suggestion and nothing about the interface requires that. Also not sure how possible that is without integrating with go. I've looked at wrapping go's test module before and it is a bit of a beast)

**Comment by akinsho** [comment]
Thanks for the fix and the pointers @rcarriga, regarding point 2 on the return for results, is the correct way to handle this then to iterate the tree somehow and match each result output from the test runner to a node of the tree? how do you account for ways that the tests might have been run? do you need to?

**Comment by akinsho** [comment]
I ended up using the `tree:iter` method and mapping each test name to each node which seemed to work. Not sure if that would work as well for larger test scopes like the whole suite etc.

**Comment by akinsho** [comment]
@rcarriga seems to work well enough now, so if you're ok with it will open a PR to add it to the list of adapters (it's still pretty beta though). One thing I'd still like some help with is I'd like to change the output content. I use the `-json` flag, so the test runner gives me easily parsable output, but that means that opening up the test output just shows JSON which isn't that readable. I'm able to collect and parse the test output, so I can re-generate the string that you'd otherwise get from a normal run of `go test` but not sure how to feed it into neotest for the output function

e.g. 
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/22454918/172695365-91de74b9-fab7-42d3-84e0-2baeee82b1df.png">

Other things I'll eventually want to tackle are
- table/list based test cases
- Different ways of running tests other than just test, file. I'd like to add an easy way to test packages not sure exactly how to expose that command

**Comment by rcarriga** [comment]
Great to hear it's working! Happy to add it to the list.

For showing readable output you could create a tempfile using `tempname()`, write the reconstructed data to it and then set the `output` field of the result objects. It's set automatically by the core client if not present to the output of the process.

>  I'd like to add an easy way to test packages not sure exactly how to expose that command

Not too familiar with go beyond the basics, can multiple packages share the same directory (meaning that running a directory wouldn't work)? It may require an additional position type to be added to core to represent it if so

**Comment by akinsho** [comment]
@rcarriga that worked re. saving output to a different file and then using that path 👍🏿. One case where I'm not sure if this works is when for whatever reason no test file is found, in this case there is no result to point my output file to, so it just uses the fallback. Tbh the case I'm explaining is an odd one since it should definitely not be saying there is no test, but I'll dig into that, I'm just wondering if there's a way to change the fallback output file to one of my own making even if there are no results

Re. the packages, I believe that is invalid in go and all files from a package must be within that folder, so I guess just using the directory runner would work.

**Comment by rcarriga** [comment]
> if there's a way to change the fallback output file to one of my own making even if there are no results

You can return a result object for any position including namespaces, files and directories. By default they're just aggregated from child tests. So just iterate through the tree and set the result output for each one to your custom one.

> Re. the packages, I believe that is invalid in go and all files from a package must be within that folder, so I guess just using the directory runner would work.

Good to hear :+1:

**Comment by akinsho** [comment]
@rcarriga thanks for your help, now the project is up I'll close this out. If I have any issues with getting other stuff working, I'll tag you in an issue on that repo if that's alright. Hopefully shouldn't be frequent.

**Comment by rcarriga** [comment]
Sounds good to me, thanks for contributing!
